// <auto-generated>
// Generated by Viva Ads from Assets/VivaAds/AdUnits.json.
// Edit the ad units and placements in Viva > Ads > Ad Units; do not edit this file.
// </auto-generated>
using UnityEngine;

namespace Viva.Services.Ads
{
    /// <summary>Ad units and placements declared in Viva > Ads > Ad Units.</summary>
    public static class AdPlacements
    {
        /// <summary>Configuration for AdsService.Initialize.</summary>
        public static AdUnitConfiguration Configuration() => new AdUnitConfiguration
        {
            Rewarded = null,
            Interstitial = null,
            Banner = null,
        };
    }
}
