// <auto-generated>
// Generated by Viva Remote Config from Assets/VivaRemoteConfig/RemoteConfigParameters.json.
// Edit the parameters in Viva > Remote Config > Parameters; do not edit this file.
// </auto-generated>
using System.Collections.Generic;

namespace Viva.Services.RemoteConfig
{
    public static class RemoteConfigParameters
    {
        /// <summary>Parameter keys, as they are in the Firebase console.</summary>
        public static class Keys
        {
        }

        /// <summary>In-app defaults, registered in Firebase by RemoteConfigService.Initialize.</summary>
        public static Dictionary<string, object> Defaults() => new Dictionary<string, object>
        {
        };
    }
}
