using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using UnityEngine;

namespace Viva.Services.Ads.Editor
{
    /// <summary>
    /// Genera AdPlacements.cs: un enum por formato activo y la configuración que consume AdsService.Initialize.
    /// Se regenera entero en cada guardado; el usuario no lo edita.
    /// </summary>
    public static class AdsCodeGenerator
    {
        public const string NAMESPACE = "Viva.Services.Ads";
        public const string CLASS_NAME = "AdPlacements";
        private const string INDENT = "    ";

        public static string Generate(AdUnitsDefinition definition, string sourceFilePath)
        {
            var code = new StringBuilder();
            code.AppendLine("// <auto-generated>");
            code.AppendLine($"// Generated by Viva Ads from {sourceFilePath}.");
            code.AppendLine("// Edit the ad units and placements in Viva > Ads > Ad Units; do not edit this file.");
            code.AppendLine("// </auto-generated>");
            code.AppendLine("using UnityEngine;");
            code.AppendLine();
            code.AppendLine($"namespace {NAMESPACE}");
            code.AppendLine("{");

            foreach (AdFormat format in Enum.GetValues(typeof(AdFormat)))
            {
                var section = definition.Get(format);
                if (section == null || !section.enabled) continue;
                AppendEnum(code, format, section);
                code.AppendLine();
            }

            code.AppendLine($"{INDENT}/// <summary>Ad units and placements declared in Viva > Ads > Ad Units.</summary>");
            code.AppendLine($"{INDENT}public static class {CLASS_NAME}");
            code.AppendLine($"{INDENT}{{");
            code.AppendLine($"{INDENT}{INDENT}/// <summary>Configuration for AdsService.Initialize.</summary>");
            code.AppendLine($"{INDENT}{INDENT}public static AdUnitConfiguration Configuration() => new AdUnitConfiguration");
            code.AppendLine($"{INDENT}{INDENT}{{");
            AppendSetup(code, AdFormat.Rewarded, definition.rewarded);
            AppendSetup(code, AdFormat.Interstitial, definition.interstitial);
            AppendBannerSetup(code, definition.banner);
            code.AppendLine($"{INDENT}{INDENT}}};");
            code.AppendLine($"{INDENT}}}");
            code.AppendLine("}");
            return code.ToString();
        }

        private static void AppendEnum(StringBuilder code, AdFormat format, AdFormatDefinition section)
        {
            code.AppendLine($"{INDENT}/// <summary>{format} placements. The name passed to the SDK is the one declared in the window.</summary>");
            code.AppendLine($"{INDENT}public enum {AdsNaming.EnumName(format)}");
            code.AppendLine($"{INDENT}{{");
            for (int i = 0; i < section.placements.Count; i++)
            {
                code.AppendLine($"{INDENT}{INDENT}/// <summary>{Escape(section.placements[i])}</summary>");
                code.AppendLine($"{INDENT}{INDENT}{AdsNaming.ToIdentifier(section.placements[i])} = {i},");
            }
            code.AppendLine($"{INDENT}}}");
        }

        private static void AppendSetup(StringBuilder code, AdFormat format, AdFormatDefinition section)
        {
            string indent = INDENT + INDENT + INDENT;
            if (section == null || !section.enabled)
            {
                code.AppendLine($"{indent}{format} = null,");
                return;
            }
            code.AppendLine($"{indent}{format} = new AdUnitSetup({StringLiteral(section.androidAdUnitId)}, {StringLiteral(section.iosAdUnitId)}, typeof({AdsNaming.EnumName(format)}), {PlacementsLiteral(section.placements)}),");
        }

        private static void AppendBannerSetup(StringBuilder code, BannerDefinition section)
        {
            string indent = INDENT + INDENT + INDENT;
            if (section == null || !section.enabled)
            {
                code.AppendLine($"{indent}Banner = null,");
                return;
            }
            string position = Enum.TryParse(section.position, out BannerPosition parsed) ? parsed.ToString() : BannerPosition.BottomCenter.ToString();
            code.AppendLine($"{indent}Banner = new BannerSetup({StringLiteral(section.androidAdUnitId)}, {StringLiteral(section.iosAdUnitId)}, typeof({AdsNaming.BANNER_ENUM}), {PlacementsLiteral(section.placements)},");
            code.AppendLine($"{indent}{INDENT}BannerPosition.{position}, {(section.adaptive ? "true" : "false")}, {ColorLiteral(section.backgroundColor)}),");
        }

        private static string PlacementsLiteral(List<string> placements)
        {
            var parts = new List<string>();
            foreach (var placement in placements) parts.Add(StringLiteral(placement));
            return "new[] { " + string.Join(", ", parts) + " }";
        }

        /// <summary>new Color(r, g, b, a) a partir de #RRGGBB o #RRGGBBAA. Negro si no parsea.</summary>
        public static string ColorLiteral(string hex)
        {
            // TryParseHtmlString deja el color en blanco cuando falla: se cae a negro explícitamente.
            if (string.IsNullOrEmpty(hex) || !ColorUtility.TryParseHtmlString(hex, out Color color)) color = Color.black;
            return $"new Color({Component(color.r)}, {Component(color.g)}, {Component(color.b)}, {Component(color.a)})";
        }

        private static string Component(float value)
        {
            string text = Math.Round(value, 4).ToString("0.0###", CultureInfo.InvariantCulture);
            return text + "f";
        }

        public static string StringLiteral(string value)
        {
            var literal = new StringBuilder("\"");
            foreach (char c in (value ?? string.Empty).Trim())
            {
                switch (c)
                {
                    case '\\': literal.Append("\\\\"); break;
                    case '"': literal.Append("\\\""); break;
                    case '\n': literal.Append("\\n"); break;
                    case '\r': literal.Append("\\r"); break;
                    case '\t': literal.Append("\\t"); break;
                    default:
                        if (c < ' ') literal.Append("\\u").Append(((int)c).ToString("x4"));
                        else literal.Append(c);
                        break;
                }
            }
            return literal.Append('"').ToString();
        }

        private static string Escape(string text)
        {
            return (text ?? string.Empty).Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
        }
    }
}
