using System;
using System.Collections.Generic;
using NUnit.Framework;
using Viva.Services.RemoteConfig.Editor;

namespace Viva.Services.RemoteConfig.Tests
{
    public class RemoteConfigCodeGeneratorTests
    {
        private static string Normalize(string text) => text.Replace("\r\n", "\n").Trim();

        [Test]
        public void Generate_ProducesTheExpectedClass()
        {
            var parameters = new List<RemoteConfigParameterDefinition>
            {
                new RemoteConfigParameterDefinition("lives", "int", "5", "Max lives per level"),
                new RemoteConfigParameterDefinition("bigNumber", "long", "3000000000"),
                new RemoteConfigParameterDefinition("ratio", "float", "2.5"),
                new RemoteConfigParameterDefinition("precise", "double", "3"),
                new RemoteConfigParameterDefinition("enabled", "bool", "true", "Feature <flag> & more"),
                new RemoteConfigParameterDefinition("nicknameAllowlist", "string", "a,\"b\"\nc"),
                new RemoteConfigParameterDefinition("idfa_list", "json", "{\"entries\":[]}", "Debug devices"),
            };

            string code = RemoteConfigCodeGenerator.Generate(parameters, "Assets/VivaRemoteConfig/RemoteConfigParameters.json");

            const string expected = @"// <auto-generated>
// Generated by Viva Remote Config from Assets/VivaRemoteConfig/RemoteConfigParameters.json.
// Edit the parameters in Viva > Remote Config > Parameters; do not edit this file.
// </auto-generated>
using System.Collections.Generic;

namespace Viva.Services.RemoteConfig
{
    public static class RemoteConfigParameters
    {
        /// <summary>Max lives per level</summary>
        public static int Lives => RemoteConfigService.GetInt(Keys.Lives, 5);

        public static long BigNumber => RemoteConfigService.GetLong(Keys.BigNumber, 3000000000L);

        public static float Ratio => RemoteConfigService.GetFloat(Keys.Ratio, 2.5f);

        public static double Precise => RemoteConfigService.GetDouble(Keys.Precise, 3.0d);

        /// <summary>Feature &lt;flag&gt; &amp; more</summary>
        public static bool Enabled => RemoteConfigService.GetBool(Keys.Enabled, true);

        public static string NicknameAllowlist => RemoteConfigService.GetString(Keys.NicknameAllowlist, ""a,\""b\""\nc"");

        /// <summary>Debug devices Raw JSON. Use IdfaList&lt;T&gt;() to parse it.</summary>
        public static string IdfaListJson => RemoteConfigService.GetString(Keys.IdfaList, ""{\""entries\"":[]}"");
        public static T IdfaList<T>(T defaultValue = default) => RemoteConfigService.GetJson(Keys.IdfaList, defaultValue);

        /// <summary>Parameter keys, as they are in the Firebase console.</summary>
        public static class Keys
        {
            public const string Lives = ""lives"";
            public const string BigNumber = ""bigNumber"";
            public const string Ratio = ""ratio"";
            public const string Precise = ""precise"";
            public const string Enabled = ""enabled"";
            public const string NicknameAllowlist = ""nicknameAllowlist"";
            public const string IdfaList = ""idfa_list"";
        }

        /// <summary>In-app defaults, registered in Firebase by RemoteConfigService.Initialize.</summary>
        public static Dictionary<string, object> Defaults() => new Dictionary<string, object>
        {
            { Keys.Lives, 5 },
            { Keys.BigNumber, 3000000000L },
            { Keys.Ratio, 2.5d },
            { Keys.Precise, 3.0d },
            { Keys.Enabled, true },
            { Keys.NicknameAllowlist, ""a,\""b\""\nc"" },
            { Keys.IdfaList, ""{\""entries\"":[]}"" },
        };
    }
}";

            Assert.AreEqual(Normalize(expected), Normalize(code));
        }

        [Test]
        public void Generate_WithoutParameters_StillCompilesShape()
        {
            string code = RemoteConfigCodeGenerator.Generate(new List<RemoteConfigParameterDefinition>(), "x.json");

            StringAssert.Contains("public static class RemoteConfigParameters", code);
            StringAssert.Contains("public static class Keys", code);
            StringAssert.Contains("public static Dictionary<string, object> Defaults() => new Dictionary<string, object>", code);
            Assert.AreEqual(1, CountOccurrences(code, "=> new Dictionary<string, object>"), "one Defaults method");
        }

        [TestCase("int", "5", "5")]
        [TestCase("int", "-12", "-12")]
        [TestCase("long", "7", "7L")]
        [TestCase("float", "2.5", "2.5f")]
        [TestCase("float", "2", "2.0f")]
        [TestCase("float", "0.1", "0.1f")]
        [TestCase("double", "1e300", "1E+300d")]
        [TestCase("double", "-0.5", "-0.5d")]
        [TestCase("bool", "true", "true")]
        [TestCase("bool", "false", "false")]
        [TestCase("string", "plain", "\"plain\"")]
        [TestCase("string", "tab\there", "\"tab\\there\"")]
        [TestCase("string", "back\\slash", "\"back\\\\slash\"")]
        [TestCase("json", "{\"a\":1}", "\"{\\\"a\\\":1}\"")]
        public void Literals(string type, string value, string expected)
        {
            Assert.AreEqual(expected, RemoteConfigCodeGenerator.Literal(type, value));
        }

        [Test]
        public void DefaultLiteral_RegistersFloatsAsDoubles()
        {
            Assert.AreEqual("2.5d", RemoteConfigCodeGenerator.DefaultLiteral("float", "2.5"));
            Assert.AreEqual("0.1d", RemoteConfigCodeGenerator.DefaultLiteral("float", "0.1"), "from the text, not from the float, so no precision is lost");
            Assert.AreEqual("5", RemoteConfigCodeGenerator.DefaultLiteral("int", "5"));
        }

        [Test]
        public void StringLiteral_EscapesControlCharacters()
        {
            Assert.AreEqual("\"a\\u0001b\\0c\\r\"", RemoteConfigCodeGenerator.StringLiteral("ab\0c\r"));
            Assert.AreEqual("\"\"", RemoteConfigCodeGenerator.StringLiteral(null));
        }

        [Test]
        public void Generate_IsCultureIndependent()
        {
            var previous = System.Threading.Thread.CurrentThread.CurrentCulture;
            try
            {
                System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("es-ES");
                string code = RemoteConfigCodeGenerator.Generate(new List<RemoteConfigParameterDefinition>
                {
                    new RemoteConfigParameterDefinition("ratio", "float", "2.5"),
                }, "x.json");
                StringAssert.Contains("GetFloat(Keys.Ratio, 2.5f)", code);
                StringAssert.Contains("{ Keys.Ratio, 2.5d }", code);
            }
            finally
            {
                System.Threading.Thread.CurrentThread.CurrentCulture = previous;
            }
        }

        private static int CountOccurrences(string text, string fragment)
        {
            int count = 0, index = 0;
            while ((index = text.IndexOf(fragment, index, StringComparison.Ordinal)) >= 0)
            {
                count++;
                index += fragment.Length;
            }
            return count;
        }
    }
}
