using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace Viva.Services.RemoteConfig.Editor
{
    /// <summary>
    /// Genera la clase RemoteConfigParameters a partir de la lista de parámetros: una propiedad tipada por
    /// parámetro, las claves como constantes en Keys y el diccionario Defaults() que se registra en Firebase.
    /// Se regenera entera en cada guardado; el usuario no la edita.
    /// </summary>
    public static class RemoteConfigCodeGenerator
    {
        public const string NAMESPACE = "Viva.Services.RemoteConfig";
        public const string CLASS_NAME = "RemoteConfigParameters";
        private const string INDENT = "    ";

        public static string Generate(IReadOnlyList<RemoteConfigParameterDefinition> parameters, string sourceFilePath)
        {
            var code = new StringBuilder();
            code.AppendLine("// <auto-generated>");
            code.AppendLine($"// Generated by Viva Remote Config from {sourceFilePath}.");
            code.AppendLine("// Edit the parameters in Viva > Remote Config > Parameters; do not edit this file.");
            code.AppendLine("// </auto-generated>");
            code.AppendLine("using System.Collections.Generic;");
            code.AppendLine();
            code.AppendLine($"namespace {NAMESPACE}");
            code.AppendLine("{");
            code.AppendLine($"{INDENT}public static class {CLASS_NAME}");
            code.AppendLine($"{INDENT}{{");

            foreach (var parameter in parameters)
            {
                AppendAccessor(code, parameter);
                code.AppendLine();
            }

            AppendKeys(code, parameters);
            code.AppendLine();
            AppendDefaults(code, parameters);

            code.AppendLine($"{INDENT}}}");
            code.AppendLine("}");
            return code.ToString();
        }

        private static void AppendAccessor(StringBuilder code, RemoteConfigParameterDefinition parameter)
        {
            string name = RemoteConfigNaming.ToIdentifier(parameter.key);
            string keyReference = $"Keys.{name}";
            string summary = SummaryText(parameter.description);
            string indent = INDENT + INDENT;

            if (parameter.type == RemoteConfigParameterTypes.JSON)
            {
                string note = "Raw JSON. Use " + name + "&lt;T&gt;() to parse it.";
                code.AppendLine($"{indent}/// <summary>{(summary != null ? summary + " " : string.Empty)}{note}</summary>");
                code.AppendLine($"{indent}public static string {name}Json => RemoteConfigService.GetString({keyReference}, {StringLiteral(parameter.defaultValue)});");
                code.AppendLine($"{indent}public static T {name}<T>(T defaultValue = default) => RemoteConfigService.GetJson({keyReference}, defaultValue);");
                return;
            }

            if (summary != null) code.AppendLine($"{indent}/// <summary>{summary}</summary>");
            code.AppendLine($"{indent}public static {CSharpType(parameter.type)} {name} => RemoteConfigService.{Getter(parameter.type)}({keyReference}, {Literal(parameter.type, parameter.defaultValue)});");
        }

        private static void AppendKeys(StringBuilder code, IReadOnlyList<RemoteConfigParameterDefinition> parameters)
        {
            string indent = INDENT + INDENT;
            code.AppendLine($"{indent}/// <summary>Parameter keys, as they are in the Firebase console.</summary>");
            code.AppendLine($"{indent}public static class Keys");
            code.AppendLine($"{indent}{{");
            foreach (var parameter in parameters)
            {
                code.AppendLine($"{indent}{INDENT}public const string {RemoteConfigNaming.ToIdentifier(parameter.key)} = {StringLiteral(parameter.key)};");
            }
            code.AppendLine($"{indent}}}");
        }

        private static void AppendDefaults(StringBuilder code, IReadOnlyList<RemoteConfigParameterDefinition> parameters)
        {
            string indent = INDENT + INDENT;
            code.AppendLine($"{indent}/// <summary>In-app defaults, registered in Firebase by RemoteConfigService.Initialize.</summary>");
            code.AppendLine($"{indent}public static Dictionary<string, object> Defaults() => new Dictionary<string, object>");
            code.AppendLine($"{indent}{{");
            foreach (var parameter in parameters)
            {
                code.AppendLine($"{indent}{INDENT}{{ Keys.{RemoteConfigNaming.ToIdentifier(parameter.key)}, {DefaultLiteral(parameter.type, parameter.defaultValue)} }},");
            }
            code.AppendLine($"{indent}}};");
        }

        public static string CSharpType(string type)
        {
            switch (type)
            {
                case RemoteConfigParameterTypes.INT: return "int";
                case RemoteConfigParameterTypes.LONG: return "long";
                case RemoteConfigParameterTypes.FLOAT: return "float";
                case RemoteConfigParameterTypes.DOUBLE: return "double";
                case RemoteConfigParameterTypes.BOOL: return "bool";
                default: return "string";
            }
        }

        private static string Getter(string type)
        {
            switch (type)
            {
                case RemoteConfigParameterTypes.INT: return "GetInt";
                case RemoteConfigParameterTypes.LONG: return "GetLong";
                case RemoteConfigParameterTypes.FLOAT: return "GetFloat";
                case RemoteConfigParameterTypes.DOUBLE: return "GetDouble";
                case RemoteConfigParameterTypes.BOOL: return "GetBool";
                default: return "GetString";
            }
        }

        /// <summary>Literal C# del valor por defecto para el accesor tipado.</summary>
        public static string Literal(string type, string value)
        {
            value = value ?? string.Empty;
            switch (type)
            {
                case RemoteConfigParameterTypes.INT:
                    return RemoteConfigConverter.TryToInt(value, out int i) ? i.ToString(CultureInfo.InvariantCulture) : "0";
                case RemoteConfigParameterTypes.LONG:
                    return (RemoteConfigConverter.TryToLong(value, out long l) ? l.ToString(CultureInfo.InvariantCulture) : "0") + "L";
                case RemoteConfigParameterTypes.FLOAT:
                    return (RemoteConfigConverter.TryToFloat(value, out float f) ? WithDecimalPoint(f.ToString("R", CultureInfo.InvariantCulture)) : "0.0") + "f";
                case RemoteConfigParameterTypes.DOUBLE:
                    return (RemoteConfigConverter.TryToDouble(value, out double d) ? WithDecimalPoint(d.ToString("R", CultureInfo.InvariantCulture)) : "0.0") + "d";
                case RemoteConfigParameterTypes.BOOL:
                    return RemoteConfigConverter.TryToBool(value, out bool b) && b ? "true" : "false";
                default:
                    return StringLiteral(value);
            }
        }

        /// <summary>Literal para Defaults(): los tipos que admite SetDefaultsAsync (int, long, double, bool, string).</summary>
        public static string DefaultLiteral(string type, string value)
        {
            if (type == RemoteConfigParameterTypes.FLOAT)
            {
                // float se registra como double para no perder decimales al pasar por Firebase.
                return Literal(RemoteConfigParameterTypes.DOUBLE, value);
            }
            return Literal(type, value);
        }

        private static string WithDecimalPoint(string number)
        {
            if (number.IndexOf('.') >= 0 || number.IndexOf('E') >= 0 || number.IndexOf('e') >= 0) return number;
            return number + ".0";
        }

        /// <summary>Literal C# entre comillas con los escapes necesarios.</summary>
        public static string StringLiteral(string value)
        {
            var literal = new StringBuilder("\"");
            foreach (char c in value ?? string.Empty)
            {
                switch (c)
                {
                    case '\\': literal.Append("\\\\"); break;
                    case '"': literal.Append("\\\""); break;
                    case '\n': literal.Append("\\n"); break;
                    case '\r': literal.Append("\\r"); break;
                    case '\t': literal.Append("\\t"); break;
                    case '\0': literal.Append("\\0"); break;
                    default:
                        if (c < ' ') literal.Append("\\u").Append(((int)c).ToString("x4"));
                        else literal.Append(c);
                        break;
                }
            }
            return literal.Append('"').ToString();
        }

        /// <summary>Descripción lista para un comentario XML (una línea, sin caracteres especiales), o null si está vacía.</summary>
        private static string SummaryText(string description)
        {
            if (string.IsNullOrWhiteSpace(description)) return null;
            var text = description.Replace("\r", " ").Replace("\n", " ").Trim();
            while (text.Contains("  ")) text = text.Replace("  ", " ");
            return text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
        }
    }
}
